version: "3.9"

services:
  open_riva:
    image: 214882929820.dkr.ecr.us-east-1.amazonaws.com/open_riva:v1.0.1         # or `build: .` if you prefer
    container_name: open_riva
    ports:
      - "7005:7005"
    # networks: #you need to turn this on when needed
    #   - whisper-net
    environment:
      # runtime settings
      WHISPER_AT_ADDRESS: http://148.251.195.218:9007
      VAD_THRESHOLD: 0.49
      # 👇 override the default 1 worker here
      UVICORN_WORKERS: ${UVICORN_WORKERS:-1}   # set 4 (or any number) in .env or CLI
      NVIDIA_VISIBLE_DEVICES: all

    deploy:                                   # remove if not using Swarm
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7006/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
